<?php

/**
 * @file
 * Weixin oauth.
 */

define('WEIXIN_RID', 4);

/**
 * Implements hook_menu().
 */
function weixin_oauth_menu() {
  $items = array();
  $items['weixin/oauth'] = array(
    'title' => 'Weixin Redirect',
    'page callback' => 'weixin_oauth_redirect',
    'access callback' => 'user_is_anonymous',
    'type' => MENU_CALLBACK,
  );

  $items['weixin/oauth/callback'] = array(
    'title' => 'Authentication callback',
    'page callback' => 'weixin_oauth_callback',
    'access callback' => 'user_is_anonymous',
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/services/weixin'] = array(
    'title' => 'Weixin oauth settings',
    'description' => 'Configure the weixin AppId and AppSecret.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('weixin_oauth_admin_settings'),
    'access arguments' => array('administer weixin'),
    'file' => 'weixin_oauth.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function weixin_oauth_permission() {
  return array(
    'administer weixin' => array(
      'title' => t('Administer Weixin'),
      'description' => t('Configure Weixin.'),
    ),
  );
}

/**
 * Menu callback: Weixin Redirect.
 */
function weixin_oauth_redirect() {
  $parameters = array(
    'appid' => variable_get('weixin_appid', ''),
    'redirect_uri' => url('weixin/oauth/callback', array('absolute' => TRUE, 'query' => array('destination' => isset($_GET['dest']) ? $_GET['dest'] : 'user'))),
    'response_type' => 'code',
    'scope' => 'snsapi_userinfo',
  );
  $oauth_url = 'https://open.weixin.qq.com/connect/oauth2/authorize';
  drupal_goto($oauth_url, array('query' => $parameters, 'fragment' => 'wechat_redirect'));
}

/**
 * Menu callback: Weixin Callback.
 */
function weixin_oauth_callback() {
  $request = $_REQUEST;

  if (isset($request['code'])) {
    $parameters = array(
      'appid' => variable_get('weixin_appid', ''),
      'secret' => variable_get('weixin_appsecret', ''),
      'code' => $request['code'],
      'grant_type' => 'authorization_code',
    );

    $param_data = array(
      'method' => 'POST',
      'data' => drupal_http_build_query($parameters),
    );

    $access_token_uri = 'https://api.weixin.qq.com/sns/oauth2/access_token';

    $http = drupal_http_request($access_token_uri, $param_data);
    $data = drupal_json_decode($http->data);
    if (!isset($data['openid'])) {
      return;
    }
    $openid = $data['openid'];
    $access_token = $data['access_token'];

    $info_uri = 'https://api.weixin.qq.com/sns/userinfo';
    $http = drupal_http_request(url($info_uri, array(
      'query' => array(
        'access_token' => $access_token,
        'openid' => $openid,
        'lang' => 'zh_CN',))));
    $info = drupal_json_decode($http->data);

    weixin_oauth_execute_user_create($info);
  }
}

function weixin_oauth_execute_user_create($info) {
  global $user;
  $openid = $info['openid'];
  $identity = 'weixin_' . $openid;
  $account = user_external_load($identity);

  if (!isset($account->uid)) {
    $name = $info['nickname'];
    $ac = user_load_by_name($name);
    if ($ac) {
      $separator = '_';
      $i = 0;
      do {
        $i++;
        $name = $info['nickname'] . $separator . $i;
      } while (user_load_by_name($name));
    }
    $roles = array();
    $roles[WEIXIN_RID] = '微信用户';
    $edit = array(
      'name' => $name,
      'status' => 1,
      'roles' => $roles,
    );
    $account = user_save(NULL, $edit);
    user_set_authmaps($account, array('authname_weixin_oauth' => $identity));
    weixin_oauth_execute_user_save($account, $info);
  }
  weixin_oauth_execute_user_login($account);
  drupal_goto();
  //@todo 跳转到手机认证页面
}

function weixin_oauth_execute_user_login($account) {
  if (empty($account) OR !isset($account->uid)) {
    return FALSE;
  }
  $form_state['uid'] = $account->uid;
  user_login_submit(array(), $form_state);
  return TRUE;
}

function weixin_oauth_execute_user_save($account, $info) {
  $values = array(
    'uid' => $account->uid,
    'phone'=> 0,
    'openid' => $info['openid'],
    'status' => 1,
    'created' => time(),
    'data' => $info,
  );
  $weixin_user = beauty_weixin_user_create($values);
  $weixin_user->save();
}

function weixin_oauth_get_followers_count() {
  $query = array(
    'grant_type' => 'client_credential',
    'appid' => variable_get('weixin_appid', ''),
    'secret' => variable_get('weixin_appsecret', ''),
  );
  $url = url('https://api.weixin.qq.com/cgi-bin/token', array('query' => $query));

  $data = file_get_contents($url);
  $result = drupal_json_decode($data);
  $access_token = $result['access_token'];

  $followers_url = 'https://api.weixin.qq.com/cgi-bin/user/get?access_token=' . $access_token;
  $followers = file_get_contents($followers_url);
  $result = drupal_json_decode($followers);

  return $result['total'];
}
