<?php

/**
 * Implements hook_menu().
 */
function beauty_world_cup_menu() {
  // Note: we can't dynamically append destination to querystring.
  // Do so at theme layer. Fix in D7?
  $items['world_cup'] = array(
    'title' => '首页',
    'page callback' => 'beauty_world_cup_pages',
    'access callback' => true,
    'file' => 'beauty_world_cup.pages.inc',
  );
  $items['world_cup/news/detail/%'] = array(
    'title' => '首页',
    'page callback' => 'beauty_world_cup_page_news_detail',
    'page arguments' => array(3),
    'access callback' => true,
    'file' => 'beauty_world_cup.pages.inc',
  );
  $items['world_cup/hair'] = array(
    'title' => '发型库',
    'page callback' => 'beauty_world_cup_pages_hair',
    'access callback' => true,
    'file' => 'beauty_world_cup.pages.inc',
  );
   $items['world_cup/works'] = array(
    'title' => '作品集',
    'page callback' => 'beauty_world_cup_pages_works',
    'access callback' => true,
    'file' => 'beauty_world_cup.pages.inc',
  );
 $items['world_cup/works/detail/%'] = array(
    'title' => '作品详情',
    'page callback' => 'beauty_world_cup_pages_works_detail',
    'page arguments' => array(3),
    'access callback' => true,
    'file' => 'beauty_world_cup.pages.inc',
  );
  $items['world_cup/hair/big/%beauty_hairstyle'] = array(
    'title' => '发型库',
    'page callback' => 'beauty_world_cup_pages_hair_big',
    'page arguments' => array(3),
    'access callback' => true,
    'file' => 'beauty_world_cup.pages.inc',
  );
  $items['world_cup/hair/advantage'] = array(
    'title' => '剪个球星头',
    'page callback' => 'beauty_world_cup_page_hair_advantage',
    'access callback' => true,
    'file' => 'beauty_world_cup.pages.inc',
  );
  $items['world_cup/video/%'] = array(
    'title' => '剪个球星头',
    'page callback' => 'beauty_world_cup_page_video',
    'page arguments' => array(2),
    'access callback' => true,
    'file' => 'beauty_world_cup.pages.inc',
  );  
  $items['world_cup/flip_card'] = array(
    'title' => '首页',
    'page callback' => 'beauty_world_cup_flip_card',
    'access callback' => true,
    'file' => 'beauty_world_cup.pages.inc',
  );  
 $items['world_cup/barber/%'] = array(
    'title' => '发型师',
    'page callback' => 'beauty_world_cup_page_barber',
    'page arguments' => array(2),
    'access callback' => true,
    'file' => 'beauty_world_cup.pages.inc',
  );  
  return $items;
}

/**
 * HOOK_theme
 */
function beauty_world_cup_theme() {
  return array(
    'beauty_world_cup_frontpage' => array(
      'template' => 'beauty-world-cup-frontpage',
      'variables' => array('banner_news' => NULL, 'frontpage_news' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_world_cup') . '/theme',
    ),
    'beauty_world_cup_news_detail' => array(
      'template' => 'beauty-world-cup-news-detail',
      'variables' => array('news' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_world_cup') . '/theme',
    ),
    'beauty_world_cup_hair' => array(
      'template' => 'beauty-world-cup-hair',
      'variables' => array('hairstyles' => NULL, 'tags' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_world_cup') . '/theme',
    ),
   'beauty_world_cup_works' => array(
      'template' => 'beauty-world-cup-works',
      'variables' => array('works' => NULL, 'tags' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_world_cup') . '/theme',
    ),
      'beauty_world_cup_works_detail' => array(
      'template' => 'beauty-world-cup-works-detail',
      'variables' => array('result' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_world_cup') . '/theme',
    ),
    'beauty_world_cup_hair_big' => array(
      'template' => 'beauty-world-cup-hair-big',
      'variables' => array('hairstyle' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_world_cup') . '/theme',
    ),
    'beauty_world_cup_hair_advantage' => array(
      'template' => 'beauty-world-cup-hair-advantage',
      'variables' => array('banner_video' => NULL, 'advantage_videos' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_world_cup') . '/theme',
    ),
    'beauty_world_cup_video' => array(
      'template' => 'beauty-world-cup-video',
      'variables' => array('video' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_world_cup') . '/theme',
    ),      
    'beauty_world_cup_flip_card' => array(
      'template' => 'beauty-world-cup-flip-card',
      'variables' => array('vars' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_world_cup') . '/theme',
    ), 
    'beauty_world_cup_barber' => array(
      'template' => 'beauty-world-cup-barber',
      'variables' => array('barber' => NULL, 'comments_uri' => NULL, 'shop' => NULL, 'works' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_world_cup') . '/theme',
    ),      
  );
}
