<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Implements hook_menu().
 */
function beauty_weibo_menu() {
  $items = array();
  $items['weibo/oauth'] = array(
    'title' => 'Weibo Redirect',
    'page callback' => 'beauty_weibo_redirect',
    'access arguments' => array('access weibo api'),      
    'type' => MENU_CALLBACK,
  );

  $items['weibo/oauth/callback'] = array(
    'title' => 'Authentication callback',
    'page callback' => 'beauty_weibo_callback',
    'access arguments' => array('access weibo api'), 
    'type' => MENU_CALLBACK,
  );
  
 $items['weibo/api'] = array(
    'title' => 'Weibo api',
    'page callback' => 'beauty_weibo_api',
    'access arguments' => array('access weibo api'),      
    'type' => MENU_CALLBACK,
  );  

  $items['admin/config/services/weibo'] = array(
    'title' => 'Weibo oauth settings',
    'description' => 'Configure the Weibo App Key and App Secret.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('beauty_weibo_admin_settings'),
    'access arguments' => array('administer weibo'),
    'file' => 'beauty_weibo.admin.inc',
  );

  return $items;
}


/**
 * Implements hook_permission().
 */
function beauty_weibo_permission() {
  return array(
    'administer weibo' => array(
      'title' => t('Administer Weibo'),
      'description' => t('Configure Weibo.'),
    ),
    'access weibo api' => array(
      'title' => t('access weibo api.'),
      'description' => t('access weibo api.'),
    ),      
  );
}

/**
 * Menu callback: Weibo Redirect.
 */
function beauty_weibo_redirect() {
  $parameters = array(
    'client_id' => variable_get('weibo_appkey', ''),
    'redirect_uri' => url('weibo/oauth/callback', array('absolute' => TRUE)),
    'response_type' => 'code',
  );
  $oauth_url = 'https://api.weibo.com/oauth2/authorize';
  drupal_goto($oauth_url, array('query' => $parameters));
}

/**
 * Menu callback: Weibo Callback.
 */
function beauty_weibo_callback() {
  $request = $_REQUEST;

  if (isset($request['code'])) {
    $parameters = array(
      'client_id' => variable_get('weibo_appkey', ''),
      'client_secret' => variable_get('weibo_appsecret', ''),
      'grant_type' => 'authorization_code',
      'redirect_uri' => url('weibo/oauth/callback', array('absolute' => TRUE)),
      'code' => $request['code'],
    );

    $param_data = array(
      'method' => 'POST',
      'data' => drupal_http_build_query($parameters),
    );

    $access_token_uri = 'https://api.weibo.com/oauth2/access_token';

    $http = drupal_http_request(url($access_token_uri, array('query' => $parameters)), $param_data);
    $data = drupal_json_decode($http->data);

    $access_token = $data['access_token'];

    $_SESSION['weibo']['access_token'] = $access_token;
    drupal_goto('weibo/api');
  }
}

function beauty_weibo_api() {
    $api = 'https://api.weibo.com/2/statuses/repost_timeline.json';
    $param = array(
        'access_token' => $_SESSION['weibo']['access_token'],
        'id' => beauty_weibo_62_to_10('Bh00K41kJ'),
        'count' => 20
        
    );
    $s = file_get_contents($api .'?' . drupal_http_build_query($param));
    dsm($s);
    dsm($param);
    return print $_SESSION['weibo']['access_token'];
}

/**
 *
 */
function beauty_weibo_custom_theme(){
    if (arg(0) == 'weibo') {
        return 'rubik';
    }
}


/** 
 * 10进制转为62进制 
 *  
 * @param integer $n 10进制数值 
 * @return string 62进制 
 */ 
function beauty_weibo_10_to_62($n) {  
    $base = 62;  
    $index = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';  
    $ret = '';  
    for($t = floor(log10($n) / log10($base)); $t >= 0; $t --) {  
        $a = floor($n / pow($base, $t));  
        $ret .= substr($index, $a, 1);  
        $n -= $a * pow($base, $t);  
    }  
    return $ret;  
}

/** 
 * 62进制转为10进制 
 * 
 * @param integer $n 62进制 
 * @return string 10进制 
 */ 
function beauty_weibo_62_to_10($s) {  
    $base = 62;  
    $index = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';  
    $ret = 0;  
    $len = strlen($s) - 1;  
    for($t = 0; $t <= $len; $t ++) {  
        $ret += strpos($index, substr($s, $t, 1)) * pow($base, $len - $t);  
    }  
    return $ret;
}