<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Implements hook_schema().
 */
function beauty_weibo_schema() {

}

/**
 * Implements hook_uninstall().
 */
function beauty_weibo_uninstall() {
  variable_del('weibo_appkey');
  variable_del('weibo_appsecret');
}
