<?php

/**
 * Implements hook_menu().
 */ 
function beauty_crm_pages_menu() {
  // Note: we can't dynamically append destination to querystring.
  // Do so at theme layer. Fix in D7?
  $items['login'] = array(
    'title' => '登陆页面',
    'page callback' => 'beauty_crm_pages_login',
    'access callback' => true,
    'file' => 'beauty_crm_pages.pages.inc',
  );
  $items['shops'] = array(
    'title' => '美发店列表',
    'page callback' => 'beauty_crm_pages_shops',
    'access callback' => true,
    'file' => 'beauty_crm_pages.pages.inc',
  );
  $items['shop/%'] = array(
    'title' => '美发店',
    'page callback' => 'beauty_crm_pages_shop',
    'page arguments' => array(1),
    'access callback' => true,
    'file' => 'beauty_crm_pages.pages.inc',
  );
   $items['barbers'] = array(
    'title' => '美发师',
    'page callback' => 'beauty_crm_pages_barbers',
    'access callback' => true,
    'file' => 'beauty_crm_pages.pages.inc',
  );
 $items['homepage'] = array(
    'title' => '首页',
    'page callback' => 'beauty_crm_pages_homepage',
    'access callback' => true,
    'file' => 'beauty_crm_pages.pages.inc',
  );
  $items['changestyle'] = array(
    'title' => '换发型',
    'page callback' => 'beauty_crm_pages_changestyle',
    'access callback' => true,
    'file' => 'beauty_crm_pages.pages.inc',
  );
  $items['usertabs'] = array(
    'title' => '会员信息',
    'page callback' => 'beauty_crm_pages_usertabs',
    'access callback' => true,
    'file' => 'beauty_crm_pages.pages.inc',
  );
 return $items;
}

/**
 * HOOK_theme
 */
function beauty_crm_pages_theme() {
  return array(
    'beauty_crm_pages_login' => array(
      'template' => 'beauty-crm-pages-login',
      'variables' => array('banner_news' => NULL, 'frontpage_news' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_crm_pages') . '/theme',
    ),
    'beauty_crm_pages_shops' => array(
      'template' => 'beauty-crm-pages-shops',
      'variables' => array('news' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_crm_pages') . '/theme',
    ),
    'beauty_crm_pages_shop' => array(
      'template' => 'beauty-crm-pages-shop',
      'variables' => array('hairstyles' => NULL, 'tags' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_crm_pages') . '/theme',
    ),
   'beauty_crm_pages_barbers' => array(
      'template' => 'beauty-crm-pages-barbers',
      'variables' => array('barbers' => NULL,'rowworks'=>NULL,'rowshops'=>NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_crm_pages') . '/theme',
    ),
      'beauty_crm_pages_homepage' => array(
      'template' => 'beauty-crm-pages-homepage',
      'variables' => array('hairstyles' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_crm_pages') . '/theme',
    ),
    'beauty_crm_pages_changestyle' => array(
      'template' => 'beauty-crm-pages-changestyle',
      'variables' => array('hairstyles' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_crm_pages') . '/theme',
    ),
    'beauty_crm_pages_usertabs' => array(
      'template' => 'beauty-crm-pages-usertabs',
      'variables' => array('banner_video' => NULL, 'advantage_videos' => NULL),
      'file' => 'theme.inc',
      'path' => drupal_get_path('module', 'beauty_crm_pages') . '/theme',
    ),
  );
}

