<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
define('CUSTOM_ADMINISTRATOR_ROLE', 6);

include_once dirname(__FILE__) . '/includes/beauty_crm_entity_beauty_shop.inc';
include_once dirname(__FILE__) . '/includes/beauty_crm_entity_beauty_barber.inc';
include_once dirname(__FILE__) . '/includes/beauty_crm_entity_beauty_hairstyle.inc';
include_once dirname(__FILE__) . '/includes/beauty_crm_entity_beauty_works.inc';
include_once dirname(__FILE__) . '/includes/beauty_crm_entity_beauty_weixin_user.inc';

function beauty_crm_entity_info() {
  $return = array(
    'beauty_shop' => array(
      'label' => '美发店',
      'base table' => 'beauty_shop',
      'uri callback' => 'entity_class_uri',
      'fieldable' => TRUE,
      'module' => 'beauty_crm',
      'entity keys' => array(
        'id' => 'sid',
        'label' => 'name',
      ),
      'bundles' => array(
        'beauty_shop' => array(
          'label' => '美发店',
          'admin' => array(
            'path' => 'admin/beauty-crm/building/beauty_shop',
            'access arguments' => array('administer users'),
          ),
        ),
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => FALSE,
        )
      ),
      // the following coder is for entity api module
      'entity class' => 'Entity',
      'controller class' => 'EntityAPIController',
      'admin ui' => array(
          'path' => 'admin/beauty-crm/content/beauty_shop',
          'file' => 'includes/beauty_crm.entity.admin.inc',
          'controller class' => 'EntityDefaultUIController' // content controller doesn't work well
      ),
      'access callback' => 'beauty_crm_entity_access_callback',
      'creation callback' => 'beauty_shop_create',
    ),

   'beauty_hairstyle' => array(
      'label' => '发型',
      'base table' => 'beauty_hairstyle',
      'uri callback' => 'entity_class_uri',
      'fieldable' => TRUE,
      'module' => 'beauty_crm',
      'entity keys' => array(
        'id' => 'hid',
        'label' => 'name',
      ),
      'bundles' => array(
        'beauty_hairstyle' => array(
          'label' => '发型',
          'admin' => array(
            'path' => 'admin/beauty-crm/building/beauty_hairstyle',
            'access arguments' => array('administer users'),
          ),
        ),
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => FALSE,
        )
      ),
      // the following coder is for entity api module
      'entity class' => 'Entity',
      'controller class' => 'BeautyHairstyleController',
      'admin ui' => array(
          'path' => 'admin/beauty-crm/content/beauty_hairstyle',
          'file' => 'includes/beauty_crm.entity.admin.inc',
          'controller class' => 'BeautyHairstyleUIController', // content controller doesn't work well
      ),
      'access callback' => 'beauty_crm_entity_access_callback',
      'creation callback' => 'beauty_hairstyle_create',
    ),

  'beauty_barber' => array(
      'label' => '美发师',
      'base table' => 'beauty_barber',
      'uri callback' => 'entity_class_uri',
      'fieldable' => TRUE,
      'module' => 'beauty_crm',
      'entity keys' => array(
        'id' => 'bid',
        'label' => 'name',
      ),
      'bundles' => array(
        'beauty_barber' => array(
          'label' => '发型',
          'admin' => array(
            'path' => 'admin/beauty-crm/building/beauty_barber',
            'access arguments' => array('administer users'),
          ),
        ),
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => FALSE,
        )
      ),
      // the following coder is for entity api module
      'entity class' => 'Entity',
      'controller class' => 'BeautyBarberController',
      'admin ui' => array(
          'path' => 'admin/beauty-crm/content/beauty_barber',
          'file' => 'includes/beauty_crm.entity.admin.inc',
          'controller class' => 'BeautyBarberUIController' // content controller doesn't work well
      ),
      'access callback' => 'beauty_crm_entity_access_callback',
      'creation callback' => 'beauty_barber_create',
    ),
  'beauty_works' => array(
      'label' => '作品集',
      'base table' => 'beauty_works',
      'uri callback' => 'entity_class_uri',
      'fieldable' => TRUE,
      'module' => 'beauty_crm',
      'entity keys' => array(
        'id' => 'wid',
        'label' => 'name',
      ),
      'bundles' => array(
        'beauty_works' => array(
          'label' => '作品集',
          'admin' => array(
            'path' => 'admin/beauty-crm/building/beauty_works',
            'access arguments' => array('administer users'),
          ),
        ),
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => FALSE,
        )
      ),
      // the following coder is for entity api module
      'entity class' => 'Entity',
      'controller class' => 'BeautyWorksController',
      'admin ui' => array(
          'path' => 'admin/beauty-crm/content/beauty_works',
          'file' => 'includes/beauty_crm.entity.admin.inc',
          'controller class' => 'EntityDefaultUIController', // content controller doesn't work well
      ),
      'access callback' => 'beauty_crm_entity_access_callback',
      'creation callback' => 'beauty_works_create',
    ),
    'beauty_weixin_user' => array(
      'label' => '微信用户',
      'base table' => 'beauty_weixin_user',
      'uri callback' => 'entity_class_uri',
      'fieldable' => TRUE,
      'module' => 'beauty_crm',
      'entity keys' => array(
        'id' => 'wxuid',
        'label' => 'phone',
      ),
      'bundles' => array(
        'beauty_weixin_user' => array(
          'label' => '微信用户',
          'admin' => array(
            'path' => 'admin/beauty-crm/building/beauty_weixin_user',
            'access arguments' => array('administer users'),
          ),
        ),
      ),
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => FALSE,
        )
      ),
      // the following coder is for entity api module
      'entity class' => 'Entity',
      'controller class' => 'EntityAPIController',
      'admin ui' => array(
          'path' => 'admin/beauty-crm/content/beauty_weixin_user',
          'file' => 'includes/beauty_crm.entity.admin.inc',
          'controller class' => 'EntityDefaultUIController' // content controller doesn't work well
      ),
      'access callback' => 'beauty_crm_entity_access_callback',
      'creation callback' => 'beauty_weixin_user_create',
    ),
  );
  return $return;
}

function beauty_crm_entity_access_callback($op, $entity, $account, $entity_type) {
  return TRUE;
}

/**
 * Implements hook_field_extra_fields().
 */
function beauty_field_extra_fields() {
  $return = array();
  $info = entity_get_info('beauty_shop');
    $return['beauty_shop']['beauty_shop'] = array(
      'form' => array(
        'phone' => array(
          'label' => '电话号码',
          'description' => t('Term name textfield'),
          'weight' => -5,
        ),
        'description' => array(
          'label' => '描述',
          'description' => t('Term description textarea'),
          'weight' => 0,
        ),
      ),
      'display' => array(
        'description' => array(
          'label' => t('Description'),
          'description' => t('Term description'),
          'weight' => 0,
        ),
      ),
    );

  return $return;
}

/**
 * hook_menu
 */

function beauty_crm_menu() {
    $items = array();

    $items['admin/beauty-crm/content/edit_picture/%beauty_hairstyle'] = array(
        'title' => '首页',
        'page callback' => 'beauty_crm_edit_hair_picture',
        'page arguments' => array(4),
        'access callback' => TRUE,
        'file' => 'beauty_crm.admin.inc'
    );

    $items['world_cup/hair/adjustment/%beauty_hairstyle'] = array(
        'title' => '换发型',
        'page callback' => 'beauty_crm_hair_picture_adjustment',
        'page arguments' => array(3),
        'access callback' => TRUE,
        'file' => 'beauty_crm.pages.inc'
    );

    $items['world_cup/hair/upload/%'] = array(
        'title' => '上传照片',
        'page callback' => 'beauty_crm_hair_picture_upload',
        'page arguments' => array(3),
        'access callback' => TRUE,
        'file' => 'beauty_crm.pages.inc'
    );

    $items['world_cup/hair/share'] = array(
        'title' => '上传照片',
        'delivery callback' => 'beauty_crm_hair_picture_share',
        'access callback' => TRUE,
        'file' => 'beauty_crm.pages.inc'
    );
    $items['admin/beauty'] = array(
        'title' => '美发管理后台',
        'delivery callback' => 'beauty_crm_admin',
        'access arguments' => array('access administration pages'),
        'file' => 'beauty_crm.admin.inc'
    );    
    return $items;
}

/**
 *
 */
function beauty_crm_custom_theme(){
    if (arg(0) == 'world_cup') {
        return  'beauty';
    }
    if (arg(0) == 'user') {
        return 'rubik';
    }
}

/**
 * hook_theme
 */
function beauty_crm_theme() {
    return array(
    'beauty_crm_edit_hair_picture' => array(
      'template' => 'beauty-crm-edit-hair-picture',
      'variables' => array('beauty_hairstyle' => NULL),
      'path' => drupal_get_path('module', 'beauty_crm') . '/theme',
      'file' => 'theme.inc'
    ),
  );
}

/**
 * 统计各类用户数量
 */
function beauty_crm_get_user_count() {
  $admin_count = db_select('users_roles', 'ur')
    ->fields('ur')
    ->condition('rid', CUSTOM_ADMINISTRATOR_ROLE)
    ->countQuery()
    ->execute()
    ->fetchField();

  $shop_count = beauty_crm_get_user_count_by_table('beauty_shop');
  $barber_count = beauty_crm_get_user_count_by_table('beauty_barber');
  $weixin_count = beauty_crm_get_user_count_by_table('beauty_weixin_user');

  $user_count = array(
    'admin' => $admin_count,
    'shop' => $shop_count,
    'barber' => $barber_count,
    'weixin' => $weixin_count,
  );

  return $user_count;
}

function beauty_crm_get_user_count_by_table($table) {
  $result = db_select($table, 't')
    ->fields('t')
    ->countQuery()
    ->execute()
    ->fetchField();

  return $result;
}
