<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

include_once dirname(__FILE__) . '/includes/beauty_crm_entity_beauty_shop.inc';
include_once dirname(__FILE__) . '/includes/beauty_crm_entity_beauty_barber.inc';
include_once dirname(__FILE__) . '/includes/beauty_crm_entity_beauty_hairstyle.inc';

function beauty_crm_entity_info() {
  $return = array(
    'beauty_shop' => array(
      'label' => '美发店',
      'base table' => 'beauty_shop',
      'uri callback' => 'entity_class_uri',
      'fieldable' => TRUE,
      'module' => 'beauty_crm',
      'entity keys' => array(
        'id' => 'sid',
        'label' => 'name',
      ),
      'bundles' => array(
        'beauty_shop' => array(
          'label' => '美发店',
          'admin' => array(
            'path' => 'admin/beauty-crm/building/beauty_shop',
            'access arguments' => array('administer users'),
          ),
        ),
      ),      
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => FALSE,
        )
      ),
      // the following coder is for entity api module
      'entity class' => 'Entity',
      'controller class' => 'EntityAPIController',
      'admin ui' => array(
          'path' => 'admin/beauty-crm/content/beauty_shop',
          'file' => 'includes/beauty_crm.entity.admin.inc',
          'controller class' => 'EntityDefaultUIController' // content controller doesn't work well
      ),
      'access callback' => 'beauty_crm_entity_access_callback',
      'creation callback' => 'beauty_shop_create',
    ),
      
   'beauty_hairstyle' => array(
      'label' => '发型',
      'base table' => 'beauty_hairstyle',
      'uri callback' => 'entity_class_uri',
      'fieldable' => TRUE,
      'module' => 'beauty_crm',
      'entity keys' => array(
        'id' => 'hid',
        'label' => 'name',
      ),
      'bundles' => array(
        'beauty_hairstyle' => array(
          'label' => '发型',
          'admin' => array(
            'path' => 'admin/beauty-crm/building/beauty_hairstyle',
            'access arguments' => array('administer users'),
          ),
        ),
      ),      
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => FALSE,
        )
      ),
      // the following coder is for entity api module
      'entity class' => 'Entity',
      'controller class' => 'EntityAPIController',
      'admin ui' => array(
          'path' => 'admin/beauty-crm/content/beauty_hairstyle',
          'file' => 'includes/beauty_crm.entity.admin.inc',
          'controller class' => 'EntityDefaultUIController' // content controller doesn't work well
      ),
      'access callback' => 'beauty_crm_entity_access_callback',
      'creation callback' => 'beauty_hairstyle_create',
    ),
     
  'beauty_barber' => array(
      'label' => '美发师',
      'base table' => 'beauty_barber',
      'uri callback' => 'entity_class_uri',
      'fieldable' => TRUE,
      'module' => 'beauty_crm',
      'entity keys' => array(
        'id' => 'bid',
        'label' => 'name',  
      ),
      'bundles' => array(
        'beauty_barber' => array(
          'label' => '发型',
          'admin' => array(
            'path' => 'admin/beauty-crm/building/beauty_barber',
            'access arguments' => array('administer users'),
          ),
        ),
      ),      
      'view modes' => array(
        'full' => array(
          'label' => t('Full content'),
          'custom settings' => FALSE,
        )
      ),
      // the following coder is for entity api module
      'entity class' => 'Entity',
      'controller class' => 'EntityAPIController',
      'admin ui' => array(
          'path' => 'admin/beauty-crm/content/beauty_barber',
          'file' => 'includes/beauty_crm.entity.admin.inc',
          'controller class' => 'EntityDefaultUIController' // content controller doesn't work well
      ),
      'access callback' => 'beauty_crm_entity_access_callback',
      'creation callback' => 'beauty_barber_create',
    ),      
  );
  return $return;
}

function beauty_crm_entity_access_callback($op, $entity, $account, $entity_type) {
  return true;
}

/**
 * Implements hook_field_extra_fields().
 */
function beauty_field_extra_fields() {
  $return = array();
  $info = entity_get_info('beauty_shop');
    $return['beauty_shop']['beauty_shop'] = array(
      'form' => array(
        'phone' => array(
          'label' => '电话号码',
          'description' => t('Term name textfield'),
          'weight' => -5,
        ),
        'description' => array(
          'label' => '描述',
          'description' => t('Term description textarea'),
          'weight' => 0,
        ),
      ),
      'display' => array(
        'description' => array(
          'label' => t('Description'),
          'description' => t('Term description'),
          'weight' => 0,
        ),
      ),
    );

  return $return;
}


